In [2]:
class Employee:
    numberOfEmployees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.numberOfEmployees+=1


def averagesalary(employee):
    total = sum(e.salary for e in employee)
    average = total / len(employee)
    return average

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self,name, family, salary, department)

print("Employee 1: ")
employee1 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Employee 2: ")
employee2 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Full Time Employee 1: ")
employee3 = FulltimeEmployee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("")
print("Number of employees: ",Employee.numberOfEmployees)
listofEmployees = [employee1, employee2]
avgsalary = averagesalary(listofEmployees)
print("Avg salary is :", avgsalary)

Employee 1: 
Enter name: nithin
Family Members: 4
Employee Salary: 99999
Employee Department: cs
Employee 2: 
Enter name: cherry
Family Members: 4
Employee Salary: 88888
Employee Department: it
Full Time Employee 1: 
Enter name: sruthi
Family Members: 4
Employee Salary: 99999999
Employee Department: cis

Number of employees:  3
Avg salary is : 94443.5


In [3]:
import numpy

random_vector = numpy.random.uniform(1, 20, 20)
print(random_vector)
print("")
print("")
reshaped_array = random_vector.reshape(4, 5)
print("")
print("")
print(reshaped_array)
reshaped_array[numpy.arange(4), numpy.argmax(reshaped_array, axis=1)] = 0
print("")
print("")
print(reshaped_array)

[ 5.26872909 19.6310342  16.89669741 15.99653785 19.1632096   5.55375443
 15.66782223 15.41435225 11.18893753 13.31943311  6.81626875  6.19709968
  5.84411586 12.50773059 16.22810806  1.12081743 17.11857214 17.24846445
 14.69192228  6.34194946]




[[ 5.26872909 19.6310342  16.89669741 15.99653785 19.1632096 ]
 [ 5.55375443 15.66782223 15.41435225 11.18893753 13.31943311]
 [ 6.81626875  6.19709968  5.84411586 12.50773059 16.22810806]
 [ 1.12081743 17.11857214 17.24846445 14.69192228  6.34194946]]


[[ 5.26872909  0.         16.89669741 15.99653785 19.1632096 ]
 [ 5.55375443  0.         15.41435225 11.18893753 13.31943311]
 [ 6.81626875  6.19709968  5.84411586 12.50773059  0.        ]
 [ 1.12081743 17.11857214  0.         14.69192228  6.34194946]]
